### ISSUE TITLE
Reduce filecoin-project org ownership

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/github-mgmt#47]
## Done Criteria
1. Reduce org ownership to only a couple of people since "org owners" have the ability to impact the github org as a whole and every repo in the org ([docs](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#permissions-for-organization-rolesare)).  This includes destructive one-way operations like repo deletion.  These people should:
   1. be active in the filecoin-project org because they are more likely to make informed decisions and 
   2. collectively represent multiple independent companies/teams.  
3. Review/reduce who has push access to github-mgmt in the org, as that is an escalation path to "org ownership" as well.  This translates to looking at the "github-mgmt stewards" team, since that team has push access to github-mgmt.   This group should be:
   1. still small (5-8)
   3. active in the org because they are more likely to make informed decisions
   4. representative of multiple independent companies/teams
5. Give the "github-mgmt Stewards" team "[moderator](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#organization-moderators)" and "[security manager](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#security-managers)" roles.
6. There should be comments above each username that has "org owner like" permissions providing a justification.

## Why Important
This is the lowest-hanging fruit to protect the filecoin-project org around overly generous permissions.  We're obviously not seeking to restrict access to code itself, and this isn't about checking some box for "good OpSec".  Some reasons we care about the OpSec here include:
1. We want to reduce the ability of malicious actors' ability to introduce vulnerabilities/bugs when they compromise a member's account.
2. We want to reduce the possibility that someone's account could be compromised and then destructive actions are taken like deleting repos.  

## Communication Channels
This issue and the connected PRs are intended to be the main communication channels.  

## Background
The filecoin-project org has accumulated a lot of permissions over the years.  This was somewhat acceptable/mitigated in the past by Protocol Labs Inc being a single company.  As Protocol Labs Inc moves to an innovation network of companies ([related blog](https://protocol.ai/blog/pl-past-present-future/)) and projects like Filecoin having more and more independent teams, we're overdue on cleaning up permissions and reevaluating past assumptions.

## Notes
1. I don't think giving moderator and security operator roles to a team can be one through github-mgmt itself. For example, I don't see any useful docs when [searching Terraform's docs](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fintegrations%2Fgithub%2Flatest%2Fdocs+moderator). It would need to be a one-time action through the GitHub UI rather than through github-mgmt.
2. For reference, a similar campaign was done in IPFS earlier in 2024 per https://github.com/ipfs/ipfs/issues/511
3. I went through all permissions listed in [github org role docs](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#permissions-for-organization-roles) and then listed how I think they could/should be handled (see the collapsed table at the bottom of https://github.com/ipfs/ipfs/issues/511#issuecomment-1947577416).

```[tasklist]
## Tasks
- [x] Temporarily escalate @BigLep permissions so can view the [audit log](https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/reviewing-the-audit-log-for-your-organization) and give the moderator and security manager permissions to the newly created teams in https://github.com/filecoin-project/github-mgmt/pull/60
- [x] PR for proposing/doing the corresponding permissions changes including the related communication: https://github.com/filecoin-project/github-mgmt/pull/61
- [x] Give the "moderators" team moderator permissions.
- [x] Give the "security-managers" team security manager permissions
- [ ] ~Revoke @BigLep's escalated permissions~ Per #61, he is keeping permissions through 2024-12-31.
- [ ] https://github.com/filecoin-project/github-mgmt/issues/65
```

**Comment by momack2** [comment]
I'm supportive of reducing org owners and also project admins - especially folks not actively involved in the project today.

I'd propose moving these folks from "admin" to "member"
    - anorth
    - jbenet
    - mishmosh
    - protocolin

Would also propose moving these folks to security mgr + moderator
    - arden-sead
    - dr-bizz
    - filecoin-helper
    - galargh
    - jmac-sead
    - laurentsenta

Also, who is dr-bizz and do they need to be an admin?

cc @smagdali @jennijuju for feedback.

**Comment by smagdali** [comment]
can confirm that @dr-bizz is Daniel Bisgrove from SEAD (but I had to go check on slack).

Approve of this effort, but would like to pull in @relotnek from FF side.

**Comment by BigLep** [comment]
@momack2 and @smagdali : thanks for the feedback.

I put my proposal for reducing org ownership here: https://github.com/filecoin-project/github-mgmt/pull/61

I had just been planning to give "[moderator](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#organization-moderators)" and "[security manager](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization#security-managers)" roles to the "github-mgmt Stewards" team, but I think it makes sense to have dedicated teams for each of these and for now to have moderators include Sead folks and security managers include FF security folks.  I'll make that change now.

**Comment by BigLep** [comment]
> Give the "moderators" team moderator permissions.
Done
<img width="963" alt="image" src="https://github.com/user-attachments/assets/93e23945-8694-437a-bb5c-1a6d48175752">

> Give the "security-managers" team security manager permissions
Done
<img width="958" alt="image" src="https://github.com/user-attachments/assets/bfb8743c-002c-41f6-b239-2b7594910acf">

**Comment by BigLep** [comment]
For closing out this issue, I need to get 2 required approvals going per https://github.com/filecoin-project/github-mgmt/issues/65 .  I'm going to wait a bit on this to see how much this is needed in practice and to allow me to tackle some other loose ends.
